CREATE TABLE IF NOT EXISTS Profile (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  avatar TEXT,
  pin TEXT,
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Whitelist (
  id TEXT PRIMARY KEY,
  profileId TEXT NOT NULL,
  tmdbId TEXT NOT NULL,
  mediaType TEXT NOT NULL,
  addedAt TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(profileId, tmdbId, mediaType),
  FOREIGN KEY(profileId) REFERENCES Profile(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TimeLimit (
  id TEXT PRIMARY KEY,
  profileId TEXT NOT NULL UNIQUE,
  dailyLimitMinutes INTEGER NOT NULL,
  updatedAt TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(profileId) REFERENCES Profile(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ActivityLog (
  id TEXT PRIMARY KEY,
  profileId TEXT NOT NULL,
  tmdbId TEXT NOT NULL,
  mediaType TEXT NOT NULL,
  watchedAt TEXT DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(profileId) REFERENCES Profile(id) ON DELETE CASCADE
);